// Looks up every character on MyAnimeList (through the free Jikan API) and
// writes their portrait URLs to client/src/data/characterImages.js.
//
//   npm run fetch-images            only fills characters that have no image yet
//   npm run fetch-images -- --force refetches everyone
//
// To use your own picture for someone, edit characterImages.js by hand
// (or drop a file in client/public/characters/ and point to "/characters/x.webp").

import { writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(here, "../../client/src/data");
const outFile = path.join(dataDir, "characterImages.js");

const { CHARACTERS } = await import(pathToFileURL(path.join(dataDir, "characters.js")).href);
let existing = {};
try {
  ({ CHARACTER_IMAGES: existing } = await import(pathToFileURL(outFile).href));
} catch {
  /* first run */
}

const force = process.argv.includes("--force");
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const norm = (s) => s.toLowerCase().replace(/[^a-z]/g, "");

async function jikan(url, tries = 3) {
  const res = await fetch(url);
  if (res.status === 429 && tries > 0) {
    await sleep(2000);
    return jikan(url, tries - 1);
  }
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
  return (await res.json()).data;
}

// MAL lists names as "Isagi, Yoichi"; match both name orders.
function sameName(malName, name) {
  const parts = malName.split(",").map((p) => p.trim());
  const variants = [malName, parts.join(" "), [...parts].reverse().join(" ")].map(norm);
  return variants.includes(norm(name));
}

const images = { ...existing };
const missed = [];

for (const c of CHARACTERS) {
  if (images[c.id] && !force) continue;
  const q = encodeURIComponent(c.name);
  try {
    const results = await jikan(`https://api.jikan.moe/v4/characters?q=${q}&order_by=favorites&sort=desc&limit=10`);
    // Results are sorted by popularity, so the first name match is the anime character.
    const match = results.find((r) => sameName(r.name, c.name));
    const url = match?.images?.webp?.image_url || match?.images?.jpg?.image_url;
    if (url && !url.includes("questionmark")) {
      images[c.id] = url;
      console.log(`✓ ${c.name}`);
    } else {
      missed.push(c.name);
      console.log(`✗ ${c.name} (no match)`);
    }
  } catch (err) {
    missed.push(c.name);
    console.log(`✗ ${c.name} (${err.message})`);
  }
  await sleep(1100); // Jikan allows about 1 request per second
}

const lines = CHARACTERS.filter((c) => images[c.id]).map((c) => `  ${c.id}: ${JSON.stringify(images[c.id])},`);
await writeFile(
  outFile,
  `// Generated by \`npm run fetch-images\` in /server (portraits from MyAnimeList).\n` +
    `// Safe to edit by hand; reruns keep existing entries unless --force is passed.\n\n` +
    `export const CHARACTER_IMAGES = {\n${lines.join("\n")}\n};\n`,
);

console.log(`\nSaved ${lines.length}/${CHARACTERS.length} images to ${path.relative(process.cwd(), outFile)}`);
if (missed.length) console.log(`Missing: ${missed.join(", ")}`);
