// Looks up every character on AniList (free GraphQL API, no key needed) and
// writes their portrait URLs to client/src/data/characterImages.js.
//
//   npm run fetch-images            only fills characters that have no image yet
//   npm run fetch-images -- --force refetches everyone
//
// To use your own picture for someone, edit characterImages.js by hand
// (or drop a file in client/public/characters/ and point to "/characters/x.webp").

import { writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(here, "../../client/src/data");
const outFile = path.join(dataDir, "characterImages.js");

const { CHARACTERS } = await import(pathToFileURL(path.join(dataDir, "characters.js")).href);
let existing = {};
try {
  ({ CHARACTER_IMAGES: existing } = await import(pathToFileURL(outFile).href));
} catch {
  /* first run */
}

const force = process.argv.includes("--force");
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
// Collapses romanization differences: Seishirou/Seishiro, Tooru/Toru, Yuu/Yu.
const norm = (s) =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[^a-z]/g, "")
    .replace(/ou|oo/g, "o")
    .replace(/uu/g, "u");

// Words that identify each series in AniList media titles.
const SERIES_TITLES = { bluelock: "bluelock", haikyuu: "haikyu" };

const QUERY = `
  query ($search: String) {
    Page(perPage: 10) {
      characters(search: $search, sort: FAVOURITES_DESC) {
        name { full alternative }
        image { large }
        media(perPage: 5) { nodes { title { romaji english } } }
      }
    }
  }`;

async function search(name, tries = 3) {
  const res = await fetch("https://graphql.anilist.co", {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json" },
    body: JSON.stringify({ query: QUERY, variables: { search: name } }),
  });
  if (res.status === 429 && tries > 0) {
    const wait = Number(res.headers.get("retry-after")) || 60;
    console.log(`  rate limited, waiting ${wait}s…`);
    await sleep(wait * 1000);
    return search(name, tries - 1);
  }
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
  return (await res.json()).data.Page.characters;
}

function sameName(result, name) {
  const target = norm(name);
  const reversed = norm(name.split(" ").reverse().join(" "));
  return [result.name.full, ...(result.name.alternative || [])].some((n) => n && [target, reversed].includes(norm(n)));
}

function inSeries(result, series) {
  const key = SERIES_TITLES[series];
  return result.media.nodes.some((m) => [m.title.romaji, m.title.english].some((t) => t && norm(t).includes(key)));
}

const images = { ...existing };
const missed = [];

for (const c of CHARACTERS) {
  if (images[c.id] && !force) continue;
  try {
    // Full name first, then surname and aliases (AniList search is picky about long vowels).
    const surname = c.name.split(" ").at(-1);
    const terms = [c.name, surname, ...c.aliases.filter((a) => a.length > 3 && norm(a) !== norm(surname))];
    let match = null;
    for (const [i, term] of terms.entries()) {
      if (i > 0) await sleep(2100);
      const results = await search(term);
      match = results.find((r) => sameName(r, c.name) && inSeries(r, c.series));
      if (match) break;
    }
    const url = match?.image?.large;
    if (url && !url.includes("default")) {
      images[c.id] = url;
      console.log(`✓ ${c.name}${match.name.full === c.name ? "" : `  (AniList: "${match.name.full}")`}`);
    } else {
      missed.push(c.name);
      console.log(`✗ ${c.name} (no match)`);
    }
  } catch (err) {
    missed.push(c.name);
    console.log(`✗ ${c.name} (${err.message})`);
  }
  await sleep(2100); // AniList allows ~30 requests per minute
}

const lines = CHARACTERS.filter((c) => images[c.id]).map((c) => `  ${c.id}: ${JSON.stringify(images[c.id])},`);
await writeFile(
  outFile,
  `// Generated by \`npm run fetch-images\` in /server (portraits from AniList).\n` +
    `// Safe to edit by hand; reruns keep existing entries unless --force is passed.\n\n` +
    `export const CHARACTER_IMAGES = {\n${lines.join("\n")}\n};\n`,
);

console.log(`\nSaved ${lines.length}/${CHARACTERS.length} images to ${path.relative(process.cwd(), outFile)}`);
if (missed.length) console.log(`Missing: ${missed.join(", ")}`);
